#!/usr/bin/env python3
"""
stub_resolver.py — shared machinery for driving ionCube-encrypted PHP files.

An encrypted library file references classes that live in *other* encrypted
files. The Loader resolves those references while loading, and raises an
ordinary PHP fatal when one is missing:

    Fatal error: Interface 'WHMCS_Payment_Filter_FilterInterface' not found

Because a fatal cannot be caught, every attempt must run in its own process.
This module owns that loop: it runs a driver script, learns the missing symbol
names from stderr, pre-declares them, and iterates to a fixpoint.

Two mechanisms, both required:

- **stub** a symbol that nothing has provided. The kind matters — the fatal
  names `Interface` / `Class` / `Trait`, and PHP rejects ``implements X`` when
  X was declared as a class.
- **skip** the stub for one specific file when that file declares the symbol
  itself (`Cannot redeclare class X`). Stubs and skips share a single key space
  (full declaration lines, not bare names) so the driver's lookup can match.

Consumers: dump_batch.py (arm56 symbol extraction), class_manifest.py
(Reflection class manifests).

SPDX-License-Identifier: MIT
"""
import os
import re
import shutil
import subprocess
import tempfile
from concurrent.futures import ThreadPoolExecutor

# "Interface 'X' not found" / "Class 'X' not found" / "Trait 'X' not found"
MISSING_RE = re.compile(r"(Interface|Class|Trait)\s+'([^']+)'\s+not found")

# "Cannot redeclare class X, because the name is already in use"
REDECLARE_RE = re.compile(
    r"Cannot (?:re)?declare (?:class|interface|trait) ([\w\\]+)")

STUB_TEMPLATES = {
    'Interface': 'interface {name} {{}}',
    'Class': 'abstract class {name} {{}}',
    'Trait': 'trait {name} {{}}',
}

# Stub preamble shared by every generated driver.
STUB_PREAMBLE = """<?php
/* generated by ioncube-strip — one target file per process */
$target   = $argv[1];
$stubfile = $argv[2];
$skipfile = $argv[3];

$skip = array();
foreach (file($skipfile, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) as $l) {
    $skip[trim($l)] = true;
}

/* Pre-declare stubs for symbols the target needs but nothing has provided.
 * A stub is a declaration and nothing more: no behaviour is invented, so this
 * cannot mask a real class that a later file provides. */
foreach (file($stubfile, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) as $line) {
    $line = trim($line);
    if ($line === '' || isset($skip[$line])) { continue; }
    if (class_exists($line, false) || interface_exists($line, false)) { continue; }
    eval($line);
}
"""


def sanitize(name):
    """Filesystem-safe name for an absolute path."""
    return ''.join(c if c.isalnum() or c in '.-_' else '_' for c in name)


class StubResolver:
    """Learns the stub set required to load a set of encrypted files.

    Stubs and skips are held as ``name -> declaration line`` mappings so the
    generated driver can compare whole declarations.
    """

    def __init__(self, php, ini, extensions, outdir, env=None, timeout=30,
                 jobs=4, rounds=8):
        self.php = php
        self.ini = ini
        self.extensions = list(extensions)
        self.outdir = outdir
        self.env = dict(env or {})
        self.timeout = timeout
        self.jobs = jobs
        self.rounds = rounds
        self.stubs = {}
        self.skip = {}
        self.status = {}

    # -- process plumbing ------------------------------------------------

    def _run(self, target, driver_body, workdir):
        """Run one attempt. Returns (returncode, stdout, stderr).

        The scratch directory holding the driver and the stub/skip lists is
        removed before returning: one attempt per file per round means an
        unremoved mkdtemp leaks a directory for every file processed.
        """
        env = dict(os.environ)
        env['PHP_INI_SCAN_DIR'] = ''
        env.update(self.env)

        cmd = [self.php, '-c', self.ini]
        for ext in self.extensions:
            cmd += ['-d', f'extension={ext}']
        cmd += ['-d', 'display_errors=stderr', '-d', 'error_reporting=E_ALL']

        tmp = tempfile.mkdtemp()
        try:
            stub_path = os.path.join(tmp, 'stubs.txt')
            skip_path = os.path.join(tmp, 'skip.txt')
            driver_path = os.path.join(tmp, 'driver.php')

            with open(stub_path, 'w', encoding='utf-8') as fh:
                fh.write('\n'.join(self.stubs[k] for k in sorted(self.stubs)))
            with open(skip_path, 'w', encoding='utf-8') as fh:
                own = self.skip.get(target, {})
                fh.write('\n'.join(own[k] for k in sorted(own)))
            with open(driver_path, 'w', encoding='utf-8') as fh:
                fh.write(driver_body)

            cmd += [driver_path, target, stub_path, skip_path]

            try:
                proc = subprocess.run(cmd, cwd=workdir, env=env,
                                      timeout=self.timeout, capture_output=True,
                                      check=False)
            except subprocess.TimeoutExpired:
                return None, '', ''

            return (proc.returncode,
                    proc.stdout.decode('utf-8', 'replace'),
                    proc.stderr.decode('utf-8', 'replace'))
        finally:
            shutil.rmtree(tmp, ignore_errors=True)

    def _classify(self, stderr):
        """Missing symbols and redeclaration clashes named in stderr."""
        missing = set()
        for kind, name in MISSING_RE.findall(stderr):
            if name not in self.stubs:
                missing.add((kind, name))
        redeclared = set(REDECLARE_RE.findall(stderr))
        return missing, redeclared

    # -- resolution loop -------------------------------------------------

    def resolve(self, targets, driver_body, success_check, capture=None):
        """Iterate until no target is blocked on a missing symbol.

        ``success_check(target)`` returns True when the attempt produced a
        usable result, in which case the target is not retried.
        ``capture(target, stdout)`` is called with each attempt's stdout, for
        drivers that report their result there rather than to a file.
        """
        for round_no in range(1, self.rounds + 1):
            todo = [t for t in targets if not self.status.get(t, {}).get('ok')]
            if not todo:
                break

            new_stubs = {}
            new_skips = {}

            def work(target):
                # self.stubs is rebound every round; bind it explicitly so the
                # closure cannot read a later set.
                saved_stubs, saved_skip = self.stubs, self.skip
                code, out, err = self._run(target, driver_body,
                                           os.path.dirname(target) or '.')
                self.stubs, self.skip = saved_stubs, saved_skip
                if capture is not None and out:
                    capture(target, out)
                return target, code, out, err

            with ThreadPoolExecutor(max_workers=self.jobs) as pool:
                for target, code, out, err in pool.map(work, todo):
                    missing, redeclared = self._classify(err)
                    ok = success_check(target) and not missing and not redeclared
                    entry = {'ok': ok}
                    if missing:
                        entry['state'] = 'missing'
                        for kind, name in missing:
                            if name not in self.stubs:
                                new_stubs[name] = STUB_TEMPLATES[kind].format(name=name)
                    elif redeclared:
                        entry['state'] = 'redeclare'
                        for name in redeclared:
                            new_skips.setdefault(target, set()).add(name)
                    elif not ok:
                        entry['state'] = 'nodump'
                        first = err.strip().split('\n')[0][:200] if err.strip() else ''
                        entry['detail'] = first
                    else:
                        entry['state'] = 'ok'
                    self.status[target] = entry

            # PHP class names are case-insensitive, and the redeclare fatal
            # reports the name lowercased. Resolve the skip against the stub
            # set case-insensitively or the skip never matches its own line.
            by_lower = {k.lower(): v for k, v in self.stubs.items()}
            for target, names in new_skips.items():
                for name in names:
                    decl = by_lower.get(name.lower())
                    if decl is None:
                        decl = STUB_TEMPLATES['Class'].format(name=name)
                    self.skip.setdefault(target, {})[name] = decl

            fresh = {k: v for k, v in new_stubs.items() if k not in self.stubs}
            self.stubs.update(fresh)

            if fresh:
                print(f'round {round_no}: learned {len(fresh)} symbol(s): '
                      f'{", ".join(sorted(fresh)[:5])}')
            elif not new_skips:
                print(f'round {round_no}: fixpoint reached')
                break
            else:
                print(f'round {round_no}: skipping stubs for '
                      f'{len(new_skips)} file(s); retrying')

        return self.status

    # -- reporting -------------------------------------------------------

    def counts(self):
        out = {}
        for state in self.status.values():
            key = state.get('state', 'pending')
            out[key] = out.get(key, 0) + 1
        return out

    def summary(self, total):
        counts = self.counts()
        print(f'\n=== summary ({total} files) ===')
        for state, n in sorted(counts.items(), key=lambda x: -x[1]):
            print(f'  {state:<10} {n:4d}  ({100 * n // total}%)')
